import {
  Wrapper,
  Headline,
  Paragraph,
  SectionTitle,
} from "./disclaimer.styles";

export const metadata = {
  title: "Disclaimer — CurioWire",
  description:
    "Editorial disclaimer for CurioWire: automated content, AI-assisted reporting, and responsibility for accuracy and expression.",
};

export default function DisclaimerPage() {
  return (
    <Wrapper>
      <Headline>Editorial Disclaimer</Headline>

      <Paragraph>
        <strong>CurioWire</strong> is an experimental digital publication built
        on automated tools, open data, and artificial intelligence. While every
        effort is made to ensure factual alignment and narrative clarity,
        content is generated or refined using algorithmic models and may not
        always represent verified or up-to-date information.
      </Paragraph>

      <SectionTitle>1. Nature of the Content</SectionTitle>
      <Paragraph>
        Articles, images, and headlines published on CurioWire are composed with
        the assistance of machine learning systems. These systems summarize,
        reinterpret, and occasionally fictionalize fragments of data, language,
        and imagery. As a result, some stories may contain inaccuracies,
        omissions, or artistic representations that do not perfectly reflect
        real-world events.
      </Paragraph>

      <Paragraph>
        Readers should treat all content as informational and exploratory, not
        as definitive reporting or professional advice.
      </Paragraph>

      <SectionTitle>2. Expression and Tone</SectionTitle>
      <Paragraph>
        The tone and language of each article are designed to evoke a
        twentieth-century editorial aesthetic — occasionally ironic, poetic, or
        dramatic. Such expression is stylistic, not ideological. Any opinions,
        implications, or interpretations expressed within the content are
        generated by algorithms and do not represent the beliefs or positions of
        CurioWire, its editors, or contributors.
      </Paragraph>

      <SectionTitle>3. Imagery and Representation</SectionTitle>
      <Paragraph>
        Visual content generated or selected by AI is intended to complement the
        narrative and theme of each article. These images should not be
        interpreted as literal or documentary evidence of the subjects depicted.
        Variations in realism, likeness, or historical accuracy are inherent to
        the creative process.
      </Paragraph>

      <SectionTitle>4. Responsibility and Liability</SectionTitle>
      <Paragraph>
        CurioWire assumes no responsibility for decisions made or opinions
        formed based on the information provided on this site. We do not warrant
        the accuracy, completeness, or suitability of any material for specific
        purposes. External links are provided for context and convenience only —
        CurioWire is not responsible for the content or policies of third-party
        sites.
      </Paragraph>

      <SectionTitle>5. Ethical and Cultural Sensitivity</SectionTitle>
      <Paragraph>
        Given the automated nature of our editorial process, some phrasing or
        associations may unintentionally appear insensitive or controversial.
        Such occurrences are never deliberate. We welcome thoughtful feedback
        and continuously refine our models to avoid harm, bias, or
        misrepresentation.
      </Paragraph>

      <Paragraph>
        For feedback, factual corrections, or ethical concerns, readers may
        reach out via our <a href="/contact">contact page</a>. Constructive
        dialogue helps improve both our editorial process and technological
        transparency.
      </Paragraph>
    </Wrapper>
  );
}
